apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-cd-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: ci-cd-service-account
  namespace: default
roleRef:
  kind: Role
  name: edit  # or any other role you wish to bind
  apiGroup: rbac.authorization.k8s.io
