apiVersion: v1
kind: Service
metadata:
  name: wisecow
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 4499  # The target port within the pod is still 4499
  selector:
    app: wisecow
