name: CI/CD Pipeline

on:
  push:
    branches: 
      - master

jobs:
  build: 
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn clean package
          if ($LASTEXITCODE -ne 0) { exit 1 }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: rohithsasupalli12/wisecow:latest

      - name: Set up Kubeconfig
        run: |
          if (!(Test-Path -Path "$HOME/.kube")) {
            New-Item -ItemType Directory -Path "$HOME/.kube"
          }
          $config = @"
apiVersion: v1
clusters:
- cluster:
    server: https://kubernetes.docker.internal:6443
    insecure-skip-tls-verify: true
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: ci-cd-service-account
  name: docker-desktop
current-context: docker-desktop
users:
- name: ci-cd-service-account
  user:
    token: ${{ secrets.KUBE_TOKEN }}
"@
          $config | Out-File -FilePath "$HOME/.kube/config" -Encoding utf8

      - name: Verify kubectl context
        run: |
          kubectl config get-contexts
          if ($LASTEXITCODE -ne 0) { exit 1 }

      - name: Check Kubernetes access
        run: |
          kubectl cluster-info
          if ($LASTEXITCODE -ne 0) { exit 1 }

      - name: List Kubernetes nodes
        run: |
          kubectl get nodes
          if ($LASTEXITCODE -ne 0) { exit 1 }

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/wisecow-deployment.yaml --validate=false
          if ($LASTEXITCODE -ne 0) { exit 1 }
          kubectl apply -f k8s/wisecow-service.yaml --validate=false
          if ($LASTEXITCODE -ne 0) { exit 1 }
