name: CI/CD Pipeline

on:
  push:
    branches: 
      - master

jobs:
  build: 
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: rohithsasupalli12/wisecow:latest

      - name: Set up Kubeconfig
        run: |
          if (-not (Test-Path -Path "$HOME\.kube")) {
            New-Item -ItemType Directory -Path "$HOME\.kube"
          }
          # Create kubeconfig file content line by line
          $kubeConfig = @"
apiVersion: v1
clusters:
- cluster:
    server: https://kubernetes.docker.internal:6443
    insecure-skip-tls-verify: true
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: ci-cd-service-account
  name: docker-desktop
current-context: docker-desktop
users:
- name: ci-cd-service-account
  user:
    token: ${{ secrets.KUBE_TOKEN }}
"@
          # Write the content to the kubeconfig file
          Set-Content -Path "$HOME\.kube\config" -Value $kubeConfig

      - name: Log kubeconfig contents
        run: Get-Content -Path "$HOME\.kube\config"

      - name: Verify kubectl context
        run: kubectl config get-contexts

      - name: Check Kubernetes access
        run: kubectl cluster-info

      - name: List Kubernetes nodes
        run: kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/wisecow-deployment.yaml --validate=false
          kubectl apply -f k8s/wisecow-service.yaml --validate=false
